name: delta_e
description: CIE color difference algorithms in Dart.
author: RagePeanut
homepage: https://github.com/RagePeanut/delta-e

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
dev_dependencies:
